env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - prettier
rules:
  quotes: [error, double]
  semi: [error, always]
  semi-style: [error, last]
  semi-spacing: [error, { before: false, after: true }]
  no-multiple-empty-lines: [error, { max: 1, maxEOF: 1 }]
  no-trailing-spaces: [error, { skipBlankLines: true }]
  no-console: [error, { allow: [warn, error] }]
  no-unused-vars: warn
  no-dupe-keys: error
  arrow-parens: [error, as-needed]
  comma-dangle: [error, always-multiline]
  prefer-const: error
  prefer-destructuring: [error, { object: true, array: false }]
  prefer-spread: error
  prefer-template: error
  no-mixed-spaces-and-tabs: error
  eqeqeq: [error, always]
  indent: [error, 2, { SwitchCase: 1 }]
  max-len: [error, { code: 120, ignoreComments: true, ignoreStrings: true, ignoreTemplateLiterals: true }]
  array-bracket-spacing: [error, never]
  comma-spacing: [error, { before: false, after: true }]
  object-curly-spacing: [error, always]
  react/react-in-jsx-scope: off
  react/jsx-indent: [error, 2]
  react/jsx-indent-props: [error, 2]
  react/jsx-curly-spacing: [error, never]
  react/jsx-tag-spacing: [error, { beforeSelfClosing: always }]
  "@typescript-eslint/ban-types": off
  react/jsx-wrap-multilines:
    - error
    - declaration: parens-new-line
      assignment: parens-new-line
      return: parens-new-line
      arrow: parens-new-line
  prettier/prettier:
  - error
  - endOfLine: auto
    printWidth: 120
    semi: true
    singleQuote: false
    tabWidth: 2
    trailingComma: all
    useTabs: false
    bracketSpacing: true
    jsxBracketSameLine: false
    jsxSingleQuote: false
    arrowParens: avoid
    proseWrap: preserve
ignorePatterns:
- .next
- node_modules
- "*.d.ts"
